name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Install dependencies
      run: npm ci  # Installs Playwright and any other dependencies listed in package-lock.json

    - name: Install Playwright Browsers (Chromium only)
      run: npx playwright install chromium  # Only install Chromium explicitly if you need it

    - name: Run Playwright tests
      run: npx playwright test --workers=4 --project=chromium # Runs the Playwright tests

    - name: Upload Playwright report
      uses: actions/upload-artifact@v3  # Updated to the latest version
      with:
        name: playwright-report
        path: playwright-report/
