name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'

    - name: Install dependencies
      run: npm ci  # This installs Playwright and any other dependencies listed in package-lock.json

    - name: Run Playwright tests
      run: npx playwright test  # Runs the Playwright tests

    - name: Upload Playwright report
      uses: actions/upload-artifact@v2
      with:
        name: playwright-report
        path: playwright-report/
